// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TaxiSoftWeb.Models;

#nullable disable

namespace TaxiSoftWeb.Migrations
{
    [DbContext(typeof(TaxisoftDbContext))]
    [Migration("20260817153128_AgregarGastosOperacion")]
    partial class AgregarGastosOperacion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TaxiSoftWeb.Models.Alerta", b =>
                {
                    b.Property<int>("IdAlerta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_alerta");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdAlerta"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(300)
                        .IsUnicode(false)
                        .HasColumnType("character varying(300)");

                    b.Property<int?>("DiasAnticipacion")
                        .HasColumnType("integer")
                        .HasColumnName("diasAnticipacion");

                    b.Property<DateTime?>("FechaDesde")
                        .HasColumnType("timestamp")
                        .HasColumnName("fechaDesde");

                    b.Property<DateTime?>("FechaHasta")
                        .HasColumnType("timestamp")
                        .HasColumnName("fechaHasta");

                    b.Property<int?>("IdEstadoA")
                        .HasColumnType("integer")
                        .HasColumnName("Id_estadoA_");

                    b.HasKey("IdAlerta")
                        .HasName("PK__Alertas__1227953E3A482B74");

                    b.HasIndex("IdEstadoA");

                    b.ToTable("Alertas");
                });

            modelBuilder.Entity("TaxiSoftWeb.Models.AlertaAutomatica", b =>
                {
                    b.Property<int>("IdAlertaAuto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_alerta_auto");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdAlertaAuto"));

                    b.Property<bool?>("Activa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasColumnName("activa")
                        .HasDefaultValueSql("true");

                    b.Property<string>("Cuil")
                        .HasMaxLength(11)
                        .IsUnicode(false)
                        .HasColumnType("character varying(11)")
                        .HasColumnName("cuil_");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(300)
                        .IsUnicode(false)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("descripcion");

                    b.Property<int?>("DiasAntelacion")
                        .HasColumnType("integer")
                        .HasColumnName("dias_antelacion");

                    b.Property<DateTime?>("FechaVencimiento")
                        .HasColumnType("date")
                        .HasColumnName("fecha_vencimiento");

                    b.Property<int?>("IdRegistroOrigen")
                        .HasColumnType("integer")
                        .HasColumnName("id_registro_origen");

                    b.Property<int?>("IdVehiculo")
                        .HasColumnType("integer")
                        .HasColumnName("id_vehiculo_");

                    b.Property<string>("TipoDocumento")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tipo_documento");

                    b.HasKey("IdAlertaAuto")
                        .HasName("PK__AlertaAutomatica");

                    b.HasIndex("Cuil");

                    b.HasIndex("IdVehiculo");

                    b.ToTable("AlertasAutomaticas");
                });

            modelBuilder.Entity("TaxiSoftWeb.Models.CalibracionTaximetro", b =>
                {
                    b.Property<int>("IdCalibracion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_calibracion");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdCalibracion"));

                    b.Property<string>("EntidadCalibradora")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("entidad_calibradora");

                    b.Property<DateTime?>("FechaCalibracion")
                        .HasColumnType("date")
                        .HasColumnName("fecha_calibracion");

                    b.Property<int?>("IdVehiculo")
                        .HasColumnType("integer")
                        .HasColumnName("id_vehiculo_");

                    b.Property<string>("NroCertificado")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nro_certificado");

                    b.Property<DateTime?>("ProximaCalibracion")
                        .HasColumnType("date")
                        .HasColumnName("proxima_calibracion");

                    b.Property<decimal?>("Valor")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("valor");

                    b.HasKey("IdCalibracion")
                        .HasName("PK__CalibracionTaximetro");

                    b.HasIndex("IdVehiculo");

                    b.ToTable("CalibracionesTaximetro");
                });

            modelBuilder.Entity("TaxiSoftWeb.Models.Carnet", b =>
                {
                    b.Property<int>("IdCarnet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_carnet");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdCarnet"));

                    b.Property<string>("NroCarnet")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("nroCarnet");

                    b.Property<DateTime?>("VtoCarnet")
                        .HasColumnType("date")
                        .HasColumnName("vtoCarnet");

                    b.HasKey("IdCarnet")
                        .HasName("PK__Carnets__1688C19283540861");

                    b.ToTable("Carnets");
                });

            modelBuilder.Entity("TaxiSoftWeb.Models.Conductore", b =>
                {
                    b.Property<string>("Cuil")
                        .HasMaxLength(11)
                        .IsUnicode(false)
                        .HasColumnType("character varying(11)")
                        .HasColumnName("cuil");

                    b.Property<bool?>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasColumnName("activo")
                        .HasDefaultValueSql("true");

                    b.Property<string>("Apellido")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("apellido");

                    b.Property<decimal?>("DepositoGarantia")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("deposito_garantia");

                    b.Property<string>("Dni")
                        .HasMaxLength(8)
                        .IsUnicode(false)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("dni");

                    b.Property<DateTime?>("FechaIngreso")
                        .HasColumnType("date")
                        .HasColumnName("fecha_ingreso");

                    b.Property<DateTime?>("FechaNacimiento")
                        .HasColumnType("date")
                        .HasColumnName("fechaNacimiento");

                    b.Property<int?>("IdCarnet")
                        .HasColumnType("integer")
                        .HasColumnName("id_carnet_");

                    b.Property<int?>("IdDomicilio")
                        .HasColumnType("integer")
                        .HasColumnName("id_domicilio_");

                    b.Property<int?>("IdPuesto")
                        .HasColumnType("integer")
                        .HasColumnName("id_puesto_");

                    b.Property<int?>("IdTurno")
                        .HasColumnType("integer")
                        .HasColumnName("id_turno_");

                    b.Property<int?>("IdVehiculo")
                        .HasColumnType("integer")
                        .HasColumnName("id_vehiculo_");

                    b.Property<decimal?>("MontoAlquiler")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("monto_alquiler");

                    b.Property<string>("Nombre")
                        .HasMaxLength(70)
                        .IsUnicode(false)
                        .HasColumnType("character varying(70)")
                        .HasColumnName("nombre");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(300)
                        .IsUnicode(false)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("observaciones");

                    b.Property<decimal?>("PorcentajeRecaudacion")
                        .HasColumnType("decimal(5, 2)")
                        .HasColumnName("porcentaje_recaudacion");

                    b.Property<string>("Telefono")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("telefono");

                    b.Property<string>("TipoAlquiler")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("tipo_alquiler");

                    b.HasKey("Cuil")
                        .HasName("PK__Conducto__2CDD98AE290E0992");

                    b.HasIndex("IdCarnet");

                    b.HasIndex("IdDomicilio");

                    b.HasIndex("IdPuesto");

                    b.HasIndex("IdTurno");

                    b.HasIndex("IdVehiculo");

                    b.ToTable("Conductores");
                });

            modelBuilder.Entity("TaxiSoftWeb.Models.Domicilio", b =>
                {
                    b.Property<int>("IdDomicilio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_domicilio");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdDomicilio"));

                    b.Property<string>("Calle")
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("calle");

                    b.Property<string>("Ciudad")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("ciudad");

                    b.Property<string>("Departamento")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("departamento");

                    b.Property<int?>("Numero")
                        .HasColumnType("integer")
                        .HasColumnName("numero");

                    b.Property<string>("Piso")
                        .HasMaxLength(4)
                        .IsUnicode(false)
                        .HasColumnType("character varying(4)")
                        .HasColumnName("piso");

                    b.HasKey("IdDomicilio")
                        .HasName("PK__Domicili__A0CCE5C2CB275F17");

                    b.ToTable("Domicilios");
                });

            modelBuilder.Entity("TaxiSoftWeb.Models.EstadosActividade", b =>
                {
                    b.Property<int>("IdEstadoA")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id_estadoA");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdEstadoA"));

                    b.Property<string>("NomEstadoA")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("nomEstadoA");

                    b.HasKey("IdEstadoA")
                        .HasName("PK__EstadosA__6B32751C2CDF43A2");

                    b.ToTable("EstadosActividades");
                });

            modelBuilder.Entity("TaxiSoftWeb.Models.EstadosPago", b =>
                {
                    b.Property<int>("IdEstadoP")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id_estadoP");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdEstadoP"));

                    b.Property<string>("NomEstadoP")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("nomEstadoP");

                    b.HasKey("IdEstadoP")
                        .HasName("PK__EstadosP__6B32750D8A15EC4E");

                    b.ToTable("EstadosPagos");
                });

            modelBuilder.Entity("TaxiSoftWeb.Models.GastoOperacion", b =>
                {
                    b.Property<int>("IdGasto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_gasto");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdGasto"));

                    b.Property<string>("Cuil")
                        .HasMaxLength(11)
                        .IsUnicode(false)
                        .HasColumnType("character varying(11)")
                        .HasColumnName("cuil_");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(300)
                        .IsUnicode(false)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("descripcion");

                    b.Property<DateTime?>("FechaGasto")
                        .HasColumnType("date")
                        .HasColumnName("fecha_gasto");

                    b.Property<int?>("IdTipoGasto")
                        .HasColumnType("integer")
                        .HasColumnName("id_tipo_gasto");

                    b.Property<int?>("IdVehiculo")
                        .HasColumnType("integer")
                        .HasColumnName("id_vehiculo_");

                    b.Property<decimal?>("Importe")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("importe");

                    b.Property<int?>("Kilometraje")
                        .HasColumnType("integer")
                        .HasColumnName("kilometraje");

                    b.Property<string>("NroFactura")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nro_factura");

                    b.HasKey("IdGasto")
                        .HasName("PK__GastoOperacion");

                    b.HasIndex("Cuil");

                    b.HasIndex("IdTipoGasto");

                    b.HasIndex("IdVehiculo");

                    b.ToTable("GastosOperaciones");
                });

            modelBuilder.Entity("TaxiSoftWeb.Models.Impuesto", b =>
                {
                    b.Property<int>("IdImpuesto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_impuesto");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdImpuesto"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("descripcion");

                    b.Property<DateTime?>("FechaVto")
                        .HasColumnType("date")
                        .HasColumnName("fechaVto");

                    b.Property<int?>("IdEstadoP")
                        .HasColumnType("integer")
                        .HasColumnName("Id_estadoP_");

                    b.Property<int?>("IdVehiculo")
                        .HasColumnType("integer")
                        .HasColumnName("id_vehiculo_");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("valor");

                    b.HasKey("IdImpuesto")
                        .HasName("PK__Impuesto__8546BDFCFB2927D6");

                    b.HasIndex("IdEstadoP");

                    b.HasIndex("IdVehiculo");

                    b.ToTable("Impuestos");
                });

            modelBuilder.Entity("TaxiSoftWeb.Models.Itv", b =>
                {
                    b.Property<int>("IdItv")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_itv");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdItv"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(300)
                        .IsUnicode(false)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("descripcion");

                    b.Property<int?>("IdVehiculo")
                        .HasColumnType("integer")
                        .HasColumnName("id_vehiculo_");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("valor");

                    b.Property<DateTime?>("VigenciaDesde")
                        .HasColumnType("date")
                        .HasColumnName("vigenciaDesde");

                    b.Property<DateTime?>("VigenciaHasta")
                        .HasColumnType("date")
                        .HasColumnName("vigenciaHasta");

                    b.HasKey("IdItv")
                        .HasName("PK__ITVs__D62ADFEEB7B3E2D0");

                    b.HasIndex("IdVehiculo");

                    b.ToTable("ITVs", (string)null);
                });

            modelBuilder.Entity("TaxiSoftWeb.Models.Mantenimiento", b =>
                {
                    b.Property<int>("IdMant")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_mant");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdMant"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(300)
                        .IsUnicode(false)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("descripcion");

                    b.Property<DateTime?>("FechaMant")
                        .HasColumnType("timestamp")
                        .HasColumnName("fechaMant");

                    b.Property<int?>("IdEstadoA")
                        .HasColumnType("integer")
                        .HasColumnName("Id_estadoA_");

                    b.Property<int?>("IdVehiculo")
                        .HasColumnType("integer")
                        .HasColumnName("id_vehiculo_");

                    b.Property<decimal?>("Valor")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("valor");

                    b.HasKey("IdMant")
                        .HasName("PK__Mantenim__6FA198DEA4AFF90B");

                    b.HasIndex("IdEstadoA");

                    b.HasIndex("IdVehiculo");

                    b.ToTable("Mantenimientos");
                });

            modelBuilder.Entity("TaxiSoftWeb.Models.Multa", b =>
                {
                    b.Property<int>("IdMulta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_multa");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdMulta"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(300)
                        .IsUnicode(false)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("descripcion");

                    b.Property<DateTime?>("FechaVto")
                        .HasColumnType("date")
                        .HasColumnName("fechaVto");

                    b.Property<int?>("IdEstadoP")
                        .HasColumnType("integer")
                        .HasColumnName("Id_estadoP_");

                    b.Property<int?>("IdVehiculo")
                        .HasColumnType("integer")
                        .HasColumnName("id_vehiculo_");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("valor");

                    b.HasKey("IdMulta")
                        .HasName("PK__Multas__295650BBD8300E64");

                    b.HasIndex("IdEstadoP");

                    b.HasIndex("IdVehiculo");

                    b.ToTable("Multas");
                });

            modelBuilder.Entity("TaxiSoftWeb.Models.Puesto", b =>
                {
                    b.Property<int>("IdPuesto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_puesto");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdPuesto"));

                    b.Property<string>("CalifProfesional")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("califProfesional");

                    b.Property<string>("TarDesepeniada")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("tarDesepeniada");

                    b.HasKey("IdPuesto")
                        .HasName("PK__Puestos__123AAB99807408D8");

                    b.ToTable("Puestos");
                });

            modelBuilder.Entity("TaxiSoftWeb.Models.RegistrosDeCaja", b =>
                {
                    b.Property<int>("IdRegistroCaja")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_registroCaja");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdRegistroCaja"));

                    b.Property<string>("Concepto")
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("concepto");

                    b.Property<string>("Cuil")
                        .HasMaxLength(11)
                        .IsUnicode(false)
                        .HasColumnType("character varying(11)")
                        .HasColumnName("cuil_");

                    b.Property<DateTime?>("FechaRegisCaja")
                        .HasColumnType("timestamp")
                        .HasColumnName("fechaRegisCaja");

                    b.Property<int?>("IdCaja")
                        .HasColumnType("integer")
                        .HasColumnName("id_caja_");

                    b.Property<int?>("IdOperacion")
                        .HasColumnType("integer")
                        .HasColumnName("id_Operacion_");

                    b.Property<int?>("IdTurno")
                        .HasColumnType("integer")
                        .HasColumnName("id_turno_");

                    b.Property<int?>("IdVehiculo")
                        .HasColumnType("integer")
                        .HasColumnName("id_vehiculo_");

                    b.Property<decimal>("Importe")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("importe");

                    b.HasKey("IdRegistroCaja")
                        .HasName("PK__Registro__53E7860F39F615BE");

                    b.HasIndex("Cuil");

                    b.HasIndex("IdCaja");

                    b.HasIndex("IdOperacion");

                    b.HasIndex("IdTurno");

                    b.HasIndex("IdVehiculo");

                    b.ToTable("RegistrosDeCajas");
                });

            modelBuilder.Entity("TaxiSoftWeb.Models.Seguro", b =>
                {
                    b.Property<int>("IdSeguro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_seguro");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdSeguro"));

                    b.Property<string>("Aseguradora")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("aseguradora");

                    b.Property<int?>("IdVehiculo")
                        .HasColumnType("integer")
                        .HasColumnName("id_vehiculo_");

                    b.Property<string>("NroPoliza")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nroPoliza");

                    b.Property<DateTime?>("VigenciaDesde")
                        .HasColumnType("date")
                        .HasColumnName("vigenciaDesde");

                    b.Property<DateTime?>("VigenciaHasta")
                        .HasColumnType("date")
                        .HasColumnName("vigenciaHasta");

                    b.HasKey("IdSeguro")
                        .HasName("PK__Seguros__D187EEFEACD72954");

                    b.HasIndex("IdVehiculo");

                    b.ToTable("Seguros");
                });

            modelBuilder.Entity("TaxiSoftWeb.Models.TipoGasto", b =>
                {
                    b.Property<int>("IdTipoGasto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_tipo_gasto");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdTipoGasto"));

                    b.Property<bool?>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasColumnName("activo")
                        .HasDefaultValueSql("true");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Nombre")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("nombre");

                    b.HasKey("IdTipoGasto")
                        .HasName("PK__TipoGasto");

                    b.ToTable("TiposDeGastos");
                });

            modelBuilder.Entity("TaxiSoftWeb.Models.TiposDeCaja", b =>
                {
                    b.Property<int>("IdCaja")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_caja");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdCaja"));

                    b.Property<bool?>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasColumnName("activo")
                        .HasDefaultValueSql("true");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("NomCaja")
                        .HasMaxLength(25)
                        .IsUnicode(false)
                        .HasColumnType("character varying(25)")
                        .HasColumnName("nomCaja");

                    b.HasKey("IdCaja")
                        .HasName("PK__TiposDeC__C71E2476F4AA21F0");

                    b.ToTable("TiposDeCajas");
                });

            modelBuilder.Entity("TaxiSoftWeb.Models.TiposDeOperacione", b =>
                {
                    b.Property<int>("IdOperacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_Operacion");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdOperacion"));

                    b.Property<string>("NomOperacion")
                        .HasMaxLength(25)
                        .IsUnicode(false)
                        .HasColumnType("character varying(25)")
                        .HasColumnName("nomOperacion");

                    b.HasKey("IdOperacion")
                        .HasName("PK__TiposDeO__20CCE2A07792461B");

                    b.ToTable("TiposDeOperaciones");
                });

            modelBuilder.Entity("TaxiSoftWeb.Models.Turno", b =>
                {
                    b.Property<int>("IdTurno")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_turno");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdTurno"));

                    b.Property<TimeSpan?>("HoraFin")
                        .HasColumnType("interval")
                        .HasColumnName("horaFin");

                    b.Property<TimeSpan?>("HoraInicio")
                        .HasColumnType("interval")
                        .HasColumnName("horaInicio");

                    b.Property<string>("NomTurno")
                        .HasMaxLength(25)
                        .IsUnicode(false)
                        .HasColumnType("character varying(25)")
                        .HasColumnName("nomTurno");

                    b.HasKey("IdTurno")
                        .HasName("PK__Turnos__C68E7397F53557B3");

                    b.ToTable("Turnos");
                });

            modelBuilder.Entity("TaxiSoftWeb.Models.Vehiculo", b =>
                {
                    b.Property<int>("IdVehiculo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_vehiculo");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdVehiculo"));

                    b.Property<bool?>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasColumnName("activo")
                        .HasDefaultValueSql("true");

                    b.Property<int?>("Anio")
                        .HasColumnType("integer")
                        .HasColumnName("anio");

                    b.Property<string>("Chapa")
                        .HasMaxLength(7)
                        .IsUnicode(false)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("chapa");

                    b.Property<decimal?>("Cilindraje")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("cilindraje");

                    b.Property<string>("Marca")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("marca");

                    b.Property<string>("Modelo")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("modelo");

                    b.Property<string>("NroChasis")
                        .HasMaxLength(17)
                        .IsUnicode(false)
                        .HasColumnType("character varying(17)")
                        .HasColumnName("nroChasis");

                    b.Property<string>("NroMotor")
                        .HasMaxLength(17)
                        .IsUnicode(false)
                        .HasColumnType("character varying(17)")
                        .HasColumnName("nroMotor");

                    b.Property<string>("Patente")
                        .HasMaxLength(7)
                        .IsUnicode(false)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("patente");

                    b.HasKey("IdVehiculo")
                        .HasName("PK__Vehiculo__F5DC0F39FEA22D64");

                    b.ToTable("Vehiculos");
                });

            modelBuilder.Entity("TaxiSoftWeb.Models.Alerta", b =>
                {
                    b.HasOne("TaxiSoftWeb.Models.EstadosActividade", "IdEstadoANavigation")
                        .WithMany("Alerta")
                        .HasForeignKey("IdEstadoA")
                        .HasConstraintName("FK__Alertas__Id_esta__571DF1D5");

                    b.Navigation("IdEstadoANavigation");
                });

            modelBuilder.Entity("TaxiSoftWeb.Models.AlertaAutomatica", b =>
                {
                    b.HasOne("TaxiSoftWeb.Models.Conductore", "CuilNavigation")
                        .WithMany("AlertasAutomaticas")
                        .HasForeignKey("Cuil")
                        .HasConstraintName("FK__AlertasAuto__cuil");

                    b.HasOne("TaxiSoftWeb.Models.Vehiculo", "IdVehiculoNavigation")
                        .WithMany("AlertasAutomaticas")
                        .HasForeignKey("IdVehiculo")
                        .HasConstraintName("FK__AlertasAuto__id_vehiculo");

                    b.Navigation("CuilNavigation");

                    b.Navigation("IdVehiculoNavigation");
                });

            modelBuilder.Entity("TaxiSoftWeb.Models.CalibracionTaximetro", b =>
                {
                    b.HasOne("TaxiSoftWeb.Models.Vehiculo", "IdVehiculoNavigation")
                        .WithMany("CalibracionesTaximetro")
                        .HasForeignKey("IdVehiculo")
                        .HasConstraintName("FK__Calibracion__id_vehiculo");

                    b.Navigation("IdVehiculoNavigation");
                });

            modelBuilder.Entity("TaxiSoftWeb.Models.Conductore", b =>
                {
                    b.HasOne("TaxiSoftWeb.Models.Carnet", "IdCarnetNavigation")
                        .WithMany("Conductores")
                        .HasForeignKey("IdCarnet")
                        .HasConstraintName("FK__Conductor__id_ca__3B75D760");

                    b.HasOne("TaxiSoftWeb.Models.Domicilio", "IdDomicilioNavigation")
                        .WithMany("Conductores")
                        .HasForeignKey("IdDomicilio")
                        .HasConstraintName("FK__Conductor__id_do__3C69FB99");

                    b.HasOne("TaxiSoftWeb.Models.Puesto", "IdPuestoNavigation")
                        .WithMany("Conductores")
                        .HasForeignKey("IdPuesto")
                        .HasConstraintName("FK__Conductor__id_pu__3A81B327");

                    b.HasOne("TaxiSoftWeb.Models.Turno", "IdTurnoNavigation")
                        .WithMany("Conductores")
                        .HasForeignKey("IdTurno")
                        .HasConstraintName("FK__Conductor__id_tu__398D8EEE");

                    b.HasOne("TaxiSoftWeb.Models.Vehiculo", "IdVehiculoNavigation")
                        .WithMany("Conductores")
                        .HasForeignKey("IdVehiculo")
                        .HasConstraintName("FK__Conductor__id_ve__38996AB5");

                    b.Navigation("IdCarnetNavigation");

                    b.Navigation("IdDomicilioNavigation");

                    b.Navigation("IdPuestoNavigation");

                    b.Navigation("IdTurnoNavigation");

                    b.Navigation("IdVehiculoNavigation");
                });

            modelBuilder.Entity("TaxiSoftWeb.Models.GastoOperacion", b =>
                {
                    b.HasOne("TaxiSoftWeb.Models.Conductore", "CuilNavigation")
                        .WithMany("GastosOperaciones")
                        .HasForeignKey("Cuil")
                        .HasConstraintName("FK__GastosOper__cuil");

                    b.HasOne("TaxiSoftWeb.Models.TipoGasto", "IdTipoGastoNavigation")
                        .WithMany("GastosOperaciones")
                        .HasForeignKey("IdTipoGasto")
                        .HasConstraintName("FK__GastosOper__id_tipo_gasto");

                    b.HasOne("TaxiSoftWeb.Models.Vehiculo", "IdVehiculoNavigation")
                        .WithMany("GastosOperaciones")
                        .HasForeignKey("IdVehiculo")
                        .HasConstraintName("FK__GastosOper__id_vehiculo");

                    b.Navigation("CuilNavigation");

                    b.Navigation("IdTipoGastoNavigation");

                    b.Navigation("IdVehiculoNavigation");
                });

            modelBuilder.Entity("TaxiSoftWeb.Models.Impuesto", b =>
                {
                    b.HasOne("TaxiSoftWeb.Models.EstadosPago", "IdEstadoPNavigation")
                        .WithMany("Impuestos")
                        .HasForeignKey("IdEstadoP")
                        .HasConstraintName("FK__Impuestos__Id_es__5070F446");

                    b.HasOne("TaxiSoftWeb.Models.Vehiculo", "IdVehiculoNavigation")
                        .WithMany("Impuestos")
                        .HasForeignKey("IdVehiculo")
                        .HasConstraintName("FK__Impuestos__id_ve__4F7CD00D");

                    b.Navigation("IdEstadoPNavigation");

                    b.Navigation("IdVehiculoNavigation");
                });

            modelBuilder.Entity("TaxiSoftWeb.Models.Itv", b =>
                {
                    b.HasOne("TaxiSoftWeb.Models.Vehiculo", "IdVehiculoNavigation")
                        .WithMany("Itvs")
                        .HasForeignKey("IdVehiculo")
                        .HasConstraintName("FK__ITVs__id_vehicul__48CFD27E");

                    b.Navigation("IdVehiculoNavigation");
                });

            modelBuilder.Entity("TaxiSoftWeb.Models.Mantenimiento", b =>
                {
                    b.HasOne("TaxiSoftWeb.Models.EstadosActividade", "IdEstadoANavigation")
                        .WithMany("Mantenimientos")
                        .HasForeignKey("IdEstadoA")
                        .HasConstraintName("FK__Mantenimi__Id_es__534D60F1");

                    b.HasOne("TaxiSoftWeb.Models.Vehiculo", "IdVehiculoNavigation")
                        .WithMany("Mantenimientos")
                        .HasForeignKey("IdVehiculo")
                        .HasConstraintName("FK__Mantenimi__id_ve__5441852A");

                    b.Navigation("IdEstadoANavigation");

                    b.Navigation("IdVehiculoNavigation");
                });

            modelBuilder.Entity("TaxiSoftWeb.Models.Multa", b =>
                {
                    b.HasOne("TaxiSoftWeb.Models.EstadosPago", "IdEstadoPNavigation")
                        .WithMany("Multa")
                        .HasForeignKey("IdEstadoP")
                        .HasConstraintName("FK__Multas__Id_estad__4BAC3F29");

                    b.HasOne("TaxiSoftWeb.Models.Vehiculo", "IdVehiculoNavigation")
                        .WithMany("Multa")
                        .HasForeignKey("IdVehiculo")
                        .HasConstraintName("FK__Multas__id_vehic__4CA06362");

                    b.Navigation("IdEstadoPNavigation");

                    b.Navigation("IdVehiculoNavigation");
                });

            modelBuilder.Entity("TaxiSoftWeb.Models.RegistrosDeCaja", b =>
                {
                    b.HasOne("TaxiSoftWeb.Models.Conductore", "CuilNavigation")
                        .WithMany("RegistrosDeCajas")
                        .HasForeignKey("Cuil")
                        .HasConstraintName("FK__Registros__cuil___4316F928");

                    b.HasOne("TaxiSoftWeb.Models.TiposDeCaja", "IdCajaNavigation")
                        .WithMany("RegistrosDeCajas")
                        .HasForeignKey("IdCaja")
                        .HasConstraintName("FK__Registros__id_ca__403A8C7D");

                    b.HasOne("TaxiSoftWeb.Models.TiposDeOperacione", "IdOperacionNavigation")
                        .WithMany("RegistrosDeCajas")
                        .HasForeignKey("IdOperacion")
                        .HasConstraintName("FK__Registros__id_Op__3F466844");

                    b.HasOne("TaxiSoftWeb.Models.Turno", "IdTurnoNavigation")
                        .WithMany("RegistrosDeCajas")
                        .HasForeignKey("IdTurno")
                        .HasConstraintName("FK__Registros__id_tu__4222D4EF");

                    b.HasOne("TaxiSoftWeb.Models.Vehiculo", "IdVehiculoNavigation")
                        .WithMany("RegistrosDeCajas")
                        .HasForeignKey("IdVehiculo")
                        .HasConstraintName("FK__Registros__id_ve__412EB0B6");

                    b.Navigation("CuilNavigation");

                    b.Navigation("IdCajaNavigation");

                    b.Navigation("IdOperacionNavigation");

                    b.Navigation("IdTurnoNavigation");

                    b.Navigation("IdVehiculoNavigation");
                });

            modelBuilder.Entity("TaxiSoftWeb.Models.Seguro", b =>
                {
                    b.HasOne("TaxiSoftWeb.Models.Vehiculo", "IdVehiculoNavigation")
                        .WithMany("Seguros")
                        .HasForeignKey("IdVehiculo")
                        .HasConstraintName("FK__Seguros__id_vehi__45F365D3");

                    b.Navigation("IdVehiculoNavigation");
                });

            modelBuilder.Entity("TaxiSoftWeb.Models.Carnet", b =>
                {
                    b.Navigation("Conductores");
                });

            modelBuilder.Entity("TaxiSoftWeb.Models.Conductore", b =>
                {
                    b.Navigation("AlertasAutomaticas");

                    b.Navigation("GastosOperaciones");

                    b.Navigation("RegistrosDeCajas");
                });

            modelBuilder.Entity("TaxiSoftWeb.Models.Domicilio", b =>
                {
                    b.Navigation("Conductores");
                });

            modelBuilder.Entity("TaxiSoftWeb.Models.EstadosActividade", b =>
                {
                    b.Navigation("Alerta");

                    b.Navigation("Mantenimientos");
                });

            modelBuilder.Entity("TaxiSoftWeb.Models.EstadosPago", b =>
                {
                    b.Navigation("Impuestos");

                    b.Navigation("Multa");
                });

            modelBuilder.Entity("TaxiSoftWeb.Models.Puesto", b =>
                {
                    b.Navigation("Conductores");
                });

            modelBuilder.Entity("TaxiSoftWeb.Models.TipoGasto", b =>
                {
                    b.Navigation("GastosOperaciones");
                });

            modelBuilder.Entity("TaxiSoftWeb.Models.TiposDeCaja", b =>
                {
                    b.Navigation("RegistrosDeCajas");
                });

            modelBuilder.Entity("TaxiSoftWeb.Models.TiposDeOperacione", b =>
                {
                    b.Navigation("RegistrosDeCajas");
                });

            modelBuilder.Entity("TaxiSoftWeb.Models.Turno", b =>
                {
                    b.Navigation("Conductores");

                    b.Navigation("RegistrosDeCajas");
                });

            modelBuilder.Entity("TaxiSoftWeb.Models.Vehiculo", b =>
                {
                    b.Navigation("AlertasAutomaticas");

                    b.Navigation("CalibracionesTaximetro");

                    b.Navigation("Conductores");

                    b.Navigation("GastosOperaciones");

                    b.Navigation("Impuestos");

                    b.Navigation("Itvs");

                    b.Navigation("Mantenimientos");

                    b.Navigation("Multa");

                    b.Navigation("RegistrosDeCajas");

                    b.Navigation("Seguros");
                });
#pragma warning restore 612, 618
        }
    }
}
